[build]
  publish = "." # Diretório de publicação na raiz do projeto
  command = ""  # Deixe em branco se não houver um comando específico de build

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
